Robert/api1
NickBurnett/cs4385 pull request #11
Opened 2023-10-11 17:40 UTC by rzrz1

Data models for tutor + tutor appointments
- Tutor register + tutor home APIs
- Tutor register: /api/tutor/register
- Tutor home: /api/tutor/home/<user_name>
Init function to connect to mongo 
Testing:
locally and made sure entries + queries work
backlog unit testing until endpoints are created

2023-10-11 19:45 UTC, NathanP9000 submitted a review, later dismissed

2023-10-11 19:45 UTC, NathanP9000 commented on src/shared_lib/connect_mongo.ts
> +const mongoose = require('mongoose')
we will have to normalize this class, because we both implement it differently.

2023-10-11 21:38 UTC, rzrz1 commented on src/shared_lib/connect_mongo.ts
> +const mongoose = require('mongoose')
i have already created the instrumentation to connect to mongo once when the server starts. there is no need to reconnect every time in the api. if you need mongoose in your api, ```const mongoose = require('mongoose')``` should work with the correct token

2023-10-11 22:49 UTC, NathanP9000 commented on src/shared_lib/connect_mongo.ts
> +const mongoose = require('mongoose')
The way I set it up lets the student schema await the connection, and then use (mongoose) the mongo db. This way we never need to call connect mongo. Then we can just send the student schema to wherever we need. That's how I set up stuff.

2023-10-11 23:09 UTC, DedsecKnight commented on src/pages/api/tutor/register.ts
> +const mongoose = require('mongoose')
Any reason why we use `require` instead of `import` here?

2023-10-11 23:19 UTC, DedsecKnight requested changes
> we will have to normalize this class, because we both implement it differently.

Can we address this first before merging this PR?

2023-10-12 01:56 UTC, NickBurnett commented on src/pages/api/tutor/register.ts
> +const mongoose = require('mongoose')
+1

2023-10-12 02:25 UTC, NickBurnett requested changes

2023-10-12 02:25 UTC, NickBurnett commented on src/schema/tutor/tutorModel.ts
> +const mongoose = require('mongoose')
Normalize this with Nathan. Probably create a separate PR with just the schema creation and rebase this one.

2023-10-12 02:25 UTC, NickBurnett commented on src/shared_lib/connect_mongo.ts
> +const mongoose = require('mongoose')
Don't use snake case for file names. Also, a better file structure would be `src/lib/mongo.ts` or something similar.

2023-10-12 02:25 UTC, NickBurnett commented on src/shared_lib/connect_mongo.ts
> +const mongoose = require('mongoose')
@DedsecKnight might have missed the `require` here, but we should use normal ES6 imports as much as possible.

2023-10-12 02:25 UTC, NickBurnett commented on src/pages/api/tutor/register.ts
> +const Tutor = mongoose.models.Tutor || require('../../../schema/tutor/tutorModel')
What's the case when `mongoose.models.Tutor` doesn't exist? Same for the one below.

2023-10-12 02:25 UTC, NickBurnett commented on src/pages/api/tutor/home/[username].ts
> +const TutorAppointment = mongoose.models.TutorAppointment || require('../../../../schema/tutor/appointmentModel')
Same as the other comment.

2023-10-12 02:25 UTC, NickBurnett commented on src/instrumentation.ts
> +    connectMongo()
Thoughts on maintaining the connection throughout the runtime @DedsecKnight?

2023-10-12 16:49 UTC, DedsecKnight commented on src/instrumentation.ts
> +    connectMongo()
If the connection persist throughout server's lifetime (as in connection won't be destroyed due to serverless), I think we definitely should go with maintaining connection throughout the runtime.

2023-10-12 16:53 UTC, rzrz1 commented on src/schema/tutor/tutorModel.ts
> +const mongoose = require('mongoose')
resolved offline

2023-10-12 16:54 UTC, rzrz1 commented on src/pages/api/tutor/register.ts
> +const Tutor = mongoose.models.Tutor || require('../../../schema/tutor/tutorModel')
schema create if it doesnt exist, this checks for override

2023-10-12 16:54 UTC, rzrz1 commented on src/pages/api/tutor/home/[username].ts
> +const TutorAppointment = mongoose.models.TutorAppointment || require('../../../../schema/tutor/appointmentModel')
above

2023-10-12 17:04 UTC, rzrz1 commented on src/instrumentation.ts
> +    connectMongo()
+1, not per api

2023-10-12 17:06 UTC, DedsecKnight commented on src/schema/tutor/appointmentModel.ts
> +    }
How are appointments being formatted as string?

2023-10-12 18:57 UTC, rzrz1 commented on src/schema/tutor/appointmentModel.ts
> +    }
most likely space separated times ex ```10/12/2023-10:00:00 10/12/2023-10:30:00``` but this can change. can do regex for type checking if needed

2023-10-12 19:00 UTC, DedsecKnight commented on src/schema/tutor/appointmentModel.ts
> +    }
Seems kinda hacky in my opinion. Can we switch to something like this for better readability? 
```js
{
    startDate: DateTime;
    endDate: DateTime; 
}
```

2023-10-12 21:28 UTC, DedsecKnight submitted a review, later dismissed
Assuming that everything is working locally, lgtm!

2023-10-12 21:31 UTC, NickBurnett commented on src/lib/mongo.ts
> +export{ connectMongo }
syntax nit (nonblocking): can just `export connectMongo` or export directly from the function header.

2023-10-12 21:33 UTC, NickBurnett requested changes
Change to 500s and lgtm

2023-10-12 21:33 UTC, NickBurnett commented on src/pages/api/tutor/home/[username].ts
> +            return res.status(400).json({message: err})
Missed this one sorry, 500.

2023-10-12 21:33 UTC, NickBurnett commented on src/pages/api/tutor/register.ts
> +            return res.status(400).json(err)
500

2023-10-12 22:12 UTC, rzrz1 commented on src/pages/api/tutor/home/[username].ts
> +            return res.status(400).json({message: err})
its ok nick

2023-10-12 22:36 UTC, NickBurnett approved these changes

2023-10-12 22:38 UTC, NathanP9000 approved these changes

2023-10-12 23:05 UTC, merged