Init skeleton of main page, add tutor display components
NickBurnett/cs4385 pull request #12
Opened 2023-10-12 00:04 UTC by danielkangel

- Adds the containing skeleton of the main page

## GIF
![tutor_display](https://github.com/NickBurnett/cs4385/assets/70451728/b41279f5-8c1e-4e57-adb8-aca1bfcbda3b)

2023-10-12 02:38 UTC, NickBurnett requested changes

2023-10-12 02:38 UTC, NickBurnett commented on public/close.svg
Probably should make these components that return SVG JSX rather than using them as raw assets.

2023-10-12 02:38 UTC, NickBurnett commented on public/default_user.jpg
Is there an SVG we can use for this?

2023-10-12 02:38 UTC, NickBurnett commented on src/components/Home/index.tsx
> +  const testTutors: Array<Tutor> = [
nit: I think most people use `Tutor[]` rather than `Array<Tutor>` but if we want to use the latter that's fine.

2023-10-12 02:38 UTC, NickBurnett commented on src/components/TutorDisplay/TutorSearch/SearchFilterPopup.tsx
> +          <img src="/close.svg" width={15} height={15} />
SVG component instead of raw source.

2023-10-12 02:38 UTC, NickBurnett commented on src/components/TutorDisplay/TutorSearch/index.tsx
> +          src="/search.svg"
SVG component instead of raw source.

2023-10-12 02:38 UTC, NickBurnett commented on src/components/TutorDisplay/TutorSearch/index.tsx
> +          <img src="/filter.svg" width="20" height="20" />
SVG component instead of raw source.

2023-10-12 02:38 UTC, NickBurnett commented on src/components/TutorDisplay/TutorSearch/SearchFilterPopup.tsx
> +interface SearchFilterPopupProps {
We should keep the component file structure consistent. Before you had `src/components/ComponentName/index.ts` and I think we should stick with that.

2023-10-12 02:38 UTC, NickBurnett commented on src/components/TutorDisplay/TutorSearch/index.tsx
> +import SearchFilterPopup from "./SearchFilterPopup";
Should probably stick with a consistent import structure, like `@/components/...`

2023-10-12 02:38 UTC, NickBurnett commented on src/components/TutorDisplay/index.tsx
> +import TutorCard from "./TutorCard";
Import structure.

2023-10-12 02:38 UTC, NickBurnett commented on src/entities.d.ts
> +interface Tutor {
We should probably put this in `src/types/entities.d.ts`.

2023-10-13 18:19 UTC, danielkangel commented on src/entities.d.ts
> +interface Tutor {
relocated

2023-10-13 18:19 UTC, danielkangel commented on src/components/TutorDisplay/TutorSearch/index.tsx
> +import SearchFilterPopup from "./SearchFilterPopup";
Resolved

2023-10-13 18:21 UTC, danielkangel commented on public/default_user.jpg
I think this should be an image. IF we were to allow profile image uploads it seems silly to have the default be an svg while the rest are rendered as jpgs or whatever. I don't think it matters too much

2023-10-13 18:22 UTC, danielkangel commented on public/close.svg
Updated all inside `@components/icons/`

2023-10-13 20:27 UTC, NickBurnett submitted a review, later dismissed

2023-10-16 23:57 UTC, NickBurnett approved these changes

2023-10-16 23:58 UTC, merged