Added student API endpoint and update availability endpoint
NickBurnett/cs4385 pull request #18
Opened 2023-10-19 05:36 UTC by DedsecKnight

2023-10-19 23:23 UTC, NickBurnett requested changes
Don't we also need an endpoint for tutor availability fetching? How are we supposed to tell from the user's perspective whether the time interval is valid?

2023-10-19 23:23 UTC, NickBurnett commented on src/lib/auth/parse-token.ts
> +export async function parseStudentAuthToken(authToken: string)  {
What exactly is this "parsing". Seems like a function to grab the user by their auth token, right?

2023-10-19 23:23 UTC, NickBurnett commented on src/pages/api/students/register.ts
> +    const hashedPassword = crypto.pbkdf2Sync(userData.password, userSalt, 1000, 64, `sha512`).toString('hex');
👏🏼

2023-10-19 23:23 UTC, NickBurnett commented on src/pages/api/students/schedule.ts
> +    if (availability.startDate <= appointmentStartDate && appointmentEndDate <= availability.endDate) {
Can we also make this a guard?

2023-10-19 23:23 UTC, NickBurnett commented on src/pages/api/students/schedule.ts
> +      await Availability.deleteOne({
Potential race condition. I would delete before creating the segmented appointment intervals.

2023-10-19 23:23 UTC, NickBurnett commented on src/pages/api/students/schedule.ts
> +      await Availability.deleteOne({
Although I think the solution might just be making the API handler synchronous, up to you.

2023-10-19 23:23 UTC, NickBurnett commented on src/schema/student/studentModel.ts
> +    passwordSalt: {
👏🏼

2023-10-19 23:23 UTC, NickBurnett commented on src/schema/student/studentModel.ts
> +    passwordSalt: string;
👏🏼

2023-10-20 19:15 UTC, rzrz1 commented on src/lib/mongo.ts
>  export async function connectMongo() {
this is a good idea 👍

2023-10-20 19:23 UTC, rzrz1 commented on src/pages/api/tutor/home/[username].ts
> +            await connectMongo();
If we are connecting it on first api, we can just get rid of the instrumentation file that registers the connection during init

I can make that change if you feel necessary

2023-10-20 19:24 UTC, rzrz1 commented
LGTM! 🚢

2023-10-20 20:27 UTC, DedsecKnight commented on src/pages/api/tutor/home/[username].ts
> +            await connectMongo();
That's be great. Thanks!

2023-10-20 20:33 UTC, DedsecKnight commented
> Don't we also need an endpoint for tutor availability fetching? How are we supposed to tell from the user's perspective whether the time interval is valid?

This should be addressed here: https://github.com/NickBurnett/cs4385/pull/18/files#diff-ab8909fe4917ad13553d5c4d620cce31829c20ff969293684c8a0baa5fca6382R41-R50

2023-10-21 04:23 UTC, rzrz1 submitted a review, later dismissed
LGTM 🚢

keep in mind that instrumentation is experimental and was the immediate solution I found for server startup. can explore other options if necessary

2023-10-23 20:21 UTC, NathanP9000 requested changes

2023-10-23 20:21 UTC, NathanP9000 commented on src/pages/api/students/schedule.ts
> +  const mongoConnection = (await connectMongo())!;
I think Robert starts the connection in the instrumentation file, so he doesn't need to call a connect function later. Should figure out if u want to do it this way or his way.

2023-10-23 20:21 UTC, NathanP9000 commented on src/pages/api/students/schedule.ts
> +  const mongoConnection = (await connectMongo())!;
I think Roberts way is nice, because you don't have to call connect mongo in every file that connects to the db

2023-10-23 20:22 UTC, NathanP9000 commented on src/pages/api/students/schedule.ts
> +  const mongoConnection = (await connectMongo())!;
Everything looks good otherwise.

2023-10-23 21:12 UTC, NickBurnett submitted a review, later dismissed

2023-10-23 21:24 UTC, DedsecKnight commented on src/pages/api/students/schedule.ts
> +  const mongoConnection = (await connectMongo())!;
Resolved through rebase and force pushed

2023-10-23 21:25 UTC, DedsecKnight commented
Added a new commit to migrate from the use of `require` to `import` as well because the `require` is not working.

2023-10-23 21:30 UTC, NickBurnett requested changes
If we're not connecting in every endpoint now, where are we doing it? From a glance I'm not convinced that the endpoints actually work.

2023-10-23 21:30 UTC, NickBurnett commented on src/pages/api/students/register.ts
> +import { connectMongo } from "@/lib/mongo";
Unused import

2023-10-23 21:30 UTC, NickBurnett commented on src/pages/api/students/schedule.ts
> +import { connectMongo } from "@/lib/mongo";
Same

2023-10-23 21:30 UTC, NickBurnett commented on src/pages/api/tutor/availability.ts
> +import { connectMongo } from '@/lib/mongo';
Same

2023-10-23 21:30 UTC, NickBurnett commented on src/pages/api/tutor/home/[username].ts
> +import { connectMongo } from '@/lib/mongo';
Same

2023-10-23 21:30 UTC, NickBurnett commented on src/pages/api/tutor/register.ts
> +import { connectMongo } from '@/lib/mongo';
Same

2023-10-23 21:36 UTC, DedsecKnight commented
> If we're not connecting in every endpoint now, where are we doing it? From a glance I'm not convinced that the endpoints actually work.

According to [here](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation), the logic in the `src/instrumentation.ts` will be run when the server started up.

2023-10-23 21:39 UTC, NickBurnett approved these changes

2023-10-23 22:37 UTC, rzrz1 approved these changes
LGTM 🚢

keep in mind that instrumentation is experimental and was the immediate solution I found for server startup logic. can explore other options if necessary

2023-10-23 23:20 UTC, merged