Nathan2
NickBurnett/cs4385 pull request #19
Opened 2023-10-20 00:21 UTC by NathanP9000

Calendar comment bare bones. Needs styling. Old backend routes I made weeks ago.

2023-10-20 15:04 UTC, NickBurnett commented
Is this meant to be reviewed? If not, please mark it as a draft.

2023-10-20 19:27 UTC, rzrz1 commented
do you mind making 2 PRs, one for front end components and another one for backend in the future? will be a bit more clear, thanks

2023-10-25 21:19 UTC, NickBurnett requested changes
I'm not that big of a fan of the auto formatter you're using and general format but I don't think we should rely on a library for something we can easily do with built-ins.

2023-10-25 21:19 UTC, NickBurnett commented on src/components/Calendar/index.tsx
> +import dayjs from 'dayjs';
Why are we using `dayjs` when we could be using the JavaScript built-in?

2023-10-25 21:19 UTC, NickBurnett commented on src/components/Calendar/index.tsx
> +          <h1 className="font-semibold"> {months[month]}, {year} </h1>
Do the gaps do anything here?

2023-10-25 21:19 UTC, NickBurnett commented on src/components/Calendar/index.tsx
> +              <h1 className="cursor-pointer"> Today </h1>
Same here.

2023-10-25 21:19 UTC, NickBurnett commented on src/components/Calendar/index.tsx
> +        <h1 className="font-bold"> Schedule for {month}/{day}/{year}</h1>
Same here.

2023-10-25 21:19 UTC, NickBurnett commented on src/components/Calendar/index.tsx
> +        <p> No Meetings for today </p>
Same here.

2023-10-25 21:19 UTC, rzrz1 commented on src/components/Calendar/index.tsx
> +
nit - remove space

2023-10-25 21:20 UTC, rzrz1 commented on src/util/calendar.ts
> +    {
nit: for (...) {
}

2023-10-25 21:21 UTC, rzrz1 commented on src/util/calendar.ts
> +
nit: remove space

2023-10-25 21:23 UTC, rzrz1 commented
agree with using react libraries for calendars. saves a lot of time doing the dates. also, please look over checkstyle before PR

2023-10-25 21:24 UTC, rzrz1 commented on src/util/calendar.ts
> +    const remaining  = 42 - dates.length;
2 spaces after var

2023-10-25 21:26 UTC, DedsecKnight requested changes

2023-10-25 21:26 UTC, DedsecKnight commented on src/components/Calendar/index.tsx
Is there any reason why we would have to build our own calendar component instead of using something [like this](https://ui.shadcn.com/docs/components/calendar)?

2023-10-25 21:27 UTC, rzrz1 commented on src/util/calendar.ts
> +export const generateDate = (month = dayjs().month(), year = dayjs().year()) => {
can just import Date and just do date.addDays(1) and date.getDate(). no need for these loops

2023-10-25 21:27 UTC, DedsecKnight commented
Also, there are some merge conflicts that need to be resolved for this PR.

2023-10-25 21:27 UTC, rzrz1 commented on src/components/Calendar/index.tsx
> +
nit - space

2023-10-25 21:27 UTC, rzrz1 commented on src/components/Calendar/index.tsx
> +
nit- space

2023-10-25 21:29 UTC, rzrz1 requested changes
try react-calendar, fix dates, fix checkstyles

2023-10-25 21:36 UTC, rzrz1 commented
there were changes since u converted this from draft to pr. go a fetch and rebase

2023-10-26 16:35 UTC, danielkangel reviewed
Screenshots in PR please 🙏

2023-10-26 19:17 UTC, NathanP9000 commented
![image](https://github.com/NickBurnett/cs4385/assets/73033177/ef7286dc-8b2d-49cd-8a93-09df2d1eeddb)

2023-10-26 19:41 UTC, rzrz1 commented
lets run `npm run build` before pushing next time

2023-10-26 19:41 UTC, rzrz1 approved these changes
if it works, LGTM 🚢

2023-10-26 19:46 UTC, rzrz1 approved these changes
LGTM 🚢

2023-10-26 19:49 UTC, NickBurnett commented
Closing this until I'm done

2023-10-26 19:49 UTC, closed without merging

2023-10-26 19:50 UTC, danielkangel commented on src/components/Calendar/index.tsx
Can you place this component in the associated home page container?