tutor appointment updates and password
NickBurnett/cs4385 pull request #21
Opened 2023-10-21 14:24 UTC by rzrz1

added passwords + password salt for tutor schema

updated tutor schema to show status of appointments

2023-10-21 21:24 UTC, DedsecKnight requested changes

2023-10-21 21:24 UTC, DedsecKnight commented on src/schema/tutor/appointmentModel.ts
> +    },
I think we might need to also differentiate `pendingRequests` and `completedAppointments` on students side as well.

2023-10-22 00:12 UTC, rzrz1 commented on src/schema/tutor/appointmentModel.ts
> +    },
sounds good, i will refactor my apis against the student apis after that is merged in (might be a bit easier for me to test as well)

2023-10-26 03:03 UTC, rzrz1 commented
https://github.com/NickBurnett/cs4385/pull/23

2023-10-26 03:03 UTC, closed without merging