Nathan4
NickBurnett/cs4385 pull request #33
Opened 2023-11-24 00:57 UTC by NathanP9000

2023-11-24 20:58 UTC, NathanP9000 commented
![image](https://github.com/NickBurnett/cs4385/assets/73033177/1eb3d382-18f5-4ee0-895e-d6b18a0182a7)

2023-11-25 15:37 UTC, rzrz1 commented on src/pages/api/tutor/availability.ts
> +  await Availability.deleteMany({ username: userData.username}).exec()
idt u need exec when u do await. can u try and lmk

2023-11-25 15:46 UTC, rzrz1 commented on src/pages/api/tutor/availability.ts
> +  await Availability.deleteMany({ username: userData.username}).exec()
instead of deleting everything, just add in the ones that are missing

2023-11-25 15:50 UTC, rzrz1 commented on src/pages/api/tutor/availability.ts
> +  for (const obj of availabilityData) {
loop through this, check if it exists, and add in if it does not

2023-11-25 15:53 UTC, rzrz1 commented on src/schema/tutor/availabilityModel.ts
> +AvailabilitySchema.index({ username: 1, startDate: 1, endDate: 1 }, { unique: true });
wat is this

2023-11-25 15:54 UTC, rzrz1 commented on src/pages/availability/index.tsx
> +                            for (let i = (indexOfFirstDay <= indexOfDay) ? indexOfDay : indexOfDay - indexOfFirstDay + 7; i+ 1 - (indexOfFirstDay <= indexOfDay ? indexOfFirstDay : 0) <= new Date(pars
use _i

2023-11-25 15:55 UTC, rzrz1 requested changes
lets not delete all before insert

2023-11-25 17:02 UTC, NathanP9000 commented on src/pages/availability/index.tsx
> +                            for (let i = (indexOfFirstDay <= indexOfDay) ? indexOfDay : indexOfDay - indexOfFirstDay + 7; i+ 1 - (indexOfFirstDay <= indexOfDay ? indexOfFirstDay : 0) <= new Date(pars
i needs to be changed to i+ 1 - (indexOfFirstDay <= indexOfDay ? indexOfFirstDay : 0) otherwise certain availabilities will not be displayed

2023-11-25 17:04 UTC, NathanP9000 commented on src/pages/api/tutor/availability.ts
> +  await Availability.deleteMany({ username: userData.username}).exec()
The problem is if an availability is deleted by a tutor, then just adding in the ones that are missing will not work, because deleted availabilities will not be deleted.

2023-11-25 17:04 UTC, NathanP9000 commented on src/pages/api/tutor/availability.ts
> +  for (const obj of availabilityData) {
^ same logic

2023-11-25 17:06 UTC, NathanP9000 commented on src/schema/tutor/availabilityModel.ts
> +AvailabilitySchema.index({ username: 1, startDate: 1, endDate: 1 }, { unique: true });
This is an index to prevent possible duplicates from being added into the availability collection. I think this is better than checking every api that accesses availability if a duplicate availability is being added.

2023-11-25 17:06 UTC, NathanP9000 commented on src/schema/tutor/availabilityModel.ts
> +AvailabilitySchema.index({ username: 1, startDate: 1, endDate: 1 }, { unique: true });
It basically makes the username, startdate, and endate the primary key for the collection

2023-11-25 17:33 UTC, NathanP9000 commented on src/pages/availability/index.tsx
> +                            for (let i = (indexOfFirstDay <= indexOfDay) ? indexOfDay : indexOfDay - indexOfFirstDay + 7; i+ 1 - (indexOfFirstDay <= indexOfDay ? indexOfFirstDay : 0) <= new Date(pars
![image](https://github.com/NickBurnett/cs4385/assets/73033177/47cd961c-f3f6-4628-8693-a919d3c2b006)

2023-11-25 17:36 UTC, NathanP9000 commented on src/pages/availability/index.tsx
> +                            for (let i = (indexOfFirstDay <= indexOfDay) ? indexOfDay : indexOfDay - indexOfFirstDay + 7; i+ 1 - (indexOfFirstDay <= indexOfDay ? indexOfFirstDay : 0) <= new Date(pars
![image](https://github.com/NickBurnett/cs4385/assets/73033177/cd44b06b-a1a1-4cd8-b224-4e7c1c8f8d39)

2023-11-25 17:38 UTC, NathanP9000 commented on src/pages/availability/index.tsx
> +                            for (let i = (indexOfFirstDay <= indexOfDay) ? indexOfDay : indexOfDay - indexOfFirstDay + 7; i+ 1 - (indexOfFirstDay <= indexOfDay ? indexOfFirstDay : 0) <= new Date(pars
So here we can see that if we use i as part of the conditional in the for loop i will run to 32, but the last calendar date for Thursday in November is the 30th. This means the November 30th will not be added into the availabilities. If we make the i + 1 - ( indexOfFirstDay <= indexOfDay ? indexOfFirstDay : 0), then the condition will have the last iteration properly have 30<=30 as the condition.

2023-11-25 20:39 UTC, rzrz1 commented on src/pages/api/tutor/availability.ts
> +  await Availability.deleteMany({ username: userData.username}).exec()
any way to split request data as new appointment and deleted appointments?
either way its fine

2023-11-25 20:44 UTC, rzrz1 approved these changes
if tested LGTM 🚢

2023-11-26 17:24 UTC, merged